import {createFileRoute} from "@tanstack/react-router";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Ban,CheckCircle2,Plus,RefreshCw,Search,LayoutDashboard,Users,WalletCards,CircleDollarSign,Headphones,MonitorPlay,Globe2,Settings,UserRound,Package,TicketPercent,Bell,ShoppingBag,Link2,Menu,X,LogOut,Activity,Clock3,ShieldCheck,Smartphone,FileUp,BarChart3} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
export const Route=createFileRoute("/admin")({component:AdminArea});
type Client={id:string;name:string;username:string;mac:string;key:string;expiresAt:string;status:string;maxDevices:number;lastAccessAt:string|null;hasSource:boolean};
const initial={name:"",username:"",password:"",mac:"",expiresAt:"",maxDevices:"1",sourceUrl:"",notes:""};
const nav=[
 ["dashboard","Dashboard",LayoutDashboard],["clientes","Clientes",Users],["financeiro","Financeiro",CircleDollarSign],["planos","Planos",WalletCards],["pedidos","Pedidos",ShoppingBag],["cupons","Cupons",TicketPercent],["avisos","Avisos",Bell],["suporte","Suporte",Headphones],["apps","Apps & Players",Smartphone],["player","Web Player",MonitorPlay],["dominios","DNS & Domínios",Globe2],["importar","Importar / Exportar",FileUp],["analytics","Mais assistidos",BarChart3],["perfil","Perfil",UserRound],["config","Configurações",Settings]
] as const;
function AdminArea(){
 const[logged,setLogged]=useState(false),[clients,setClients]=useState<Client[]>([]),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[login,setLogin]=useState({username:"admin",password:""}),[form,setForm]=useState(initial),[section,setSection]=useState("dashboard"),[mobile,setMobile]=useState(false);
 async function load(){const r=await fetch("/api/admin/clients");if(r.ok){setLogged(true);setClients((await r.json()).clients)}}
 useEffect(()=>{load()},[]);
 async function signIn(e:FormEvent){e.preventDefault();const r=await fetch("/api/auth/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)}),d=await r.json();if(!r.ok)return setMessage(d.error);setLogged(true);setMessage("");load()}
 async function create(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setMessage(d.error);setForm(initial);setMessage("Cliente criado com sucesso.");load()}
 async function update(id:string,changes:Record<string,unknown>){const r=await fetch(`/api/admin/clients/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});if(r.ok)load()}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.reload()}
 if(!logged)return <div className="panel-page panel-centered"><main className="login-card"><img className="login-logo" src="/logo-maxonplay.svg"/><p className="panel-kicker">PAINEL ADMINISTRATIVO</p><h1>MAXON PLAY</h1><form onSubmit={signIn}><label>Usuário</label><Input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><label>Senha administrativa</label><Input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><Button className="w-full" size="lg">Entrar</Button>{message&&<p className="form-message">{message}</p>}</form></main></div>;
 const now=Date.now(), active=clients.filter(c=>c.status==='active'&&new Date(c.expiresAt).getTime()>=now), blocked=clients.filter(c=>c.status!=='active'), expiring=clients.filter(c=>{const d=new Date(c.expiresAt).getTime()-now;return d>=0&&d<=7*864e5}), visible=clients.filter(c=>`${c.name} ${c.username} ${c.mac}`.toLowerCase().includes(search.toLowerCase()));
 const title=nav.find(n=>n[0]===section)?.[1]||'Dashboard';
 return <div className="mx-admin"><aside className={mobile?"mx-side open":"mx-side"}><div className="mx-brand"><img src="/logo-maxonplay.svg"/><button onClick={()=>setMobile(false)}><X/></button></div><div className="mx-user"><div>MR</div><span><b>Administrador</b><small>MAXON PLAY</small></span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setMobile(false)}}><Icon/>{label}</button>)}</nav><button className="mx-logout" onClick={logout}><LogOut/> Sair</button></aside><main className="mx-main"><header className="mx-top"><button className="mx-menu" onClick={()=>setMobile(true)}><Menu/></button><div><small>MAXON PLAY / ADMIN</small><h1>{title}</h1></div><span className="mx-online"><i/> Online</span></header>{section==='dashboard'?<Dashboard clients={clients} active={active.length} blocked={blocked.length} expiring={expiring.length} onGo={()=>setSection('clientes')}/>:section==='clientes'?<Clients clients={visible} all={clients} search={search} setSearch={setSearch} form={form} setForm={setForm} create={create} update={update} message={message}/>:section==='player'?<Module title="Web Player" text="Abra o player MAXON PLAY para testar conteúdos e fontes autorizadas." action={<a className="mx-action" href="/player">Abrir Web Player</a>} icon={<MonitorPlay/>}/>:section==='planos'?<Plans/>:<Module title={title} text={moduleText(section)} icon={moduleIcon(section)}/>}</main></div>
}
function Dashboard({clients,active,blocked,expiring,onGo}:{clients:Client[],active:number,blocked:number,expiring:number,onGo:()=>void}){const accessed=clients.filter(c=>c.lastAccessAt).length;return <><section className="mx-cards"><Stat label="Clientes ativos" value={active} icon={<CheckCircle2/>}/><Stat label="Bloqueados" value={blocked} icon={<Ban/>}/><Stat label="A vencer (7 dias)" value={expiring} icon={<Clock3/>}/><Stat label="Com acessos" value={accessed} icon={<Activity/>}/></section><section className="mx-grid"><article className="mx-box mx-chart"><div className="mx-box-title"><div><small>VISÃO GERAL</small><h2>Clientes e assinaturas</h2></div><button onClick={onGo}>Gerenciar clientes</button></div><div className="mx-bars"><div style={{height:`${Math.max(12,active*18)}px`}}><span>Ativos</span></div><div style={{height:`${Math.max(12,blocked*18)}px`}}><span>Bloq.</span></div><div style={{height:`${Math.max(12,expiring*18)}px`}}><span>A vencer</span></div><div style={{height:`${Math.max(12,clients.length*18)}px`}}><span>Total</span></div></div></article><article className="mx-box"><div className="mx-box-title"><div><small>RESUMO</small><h2>Status da operação</h2></div></div><div className="mx-status-list"><p><ShieldCheck/> Painel administrativo <b>Operacional</b></p><p><Users/> Clientes cadastrados <b>{clients.length}</b></p><p><MonitorPlay/> Web Player <b>Disponível</b></p><p><Globe2/> Ambiente <b>Square Cloud</b></p></div></article></section><section className="mx-box"><div className="mx-box-title"><div><small>CLIENTES</small><h2>Últimos cadastros</h2></div></div><div className="mx-mini-table">{clients.slice(-5).reverse().map(c=><div key={c.id}><span><b>{c.name}</b><small>@{c.username}</small></span><span>{new Date(c.expiresAt).toLocaleDateString('pt-BR')}</span><em className={c.status==='active'?'ok':'no'}>{c.status==='active'?'Ativo':'Bloqueado'}</em></div>)}{!clients.length&&<p className="mx-empty">Nenhum cliente cadastrado ainda.</p>}</div></section></>}
function Stat({label,value,icon}:{label:string,value:number,icon:React.ReactNode}){return <article className="mx-stat"><div>{icon}</div><span>{label}</span><strong>{value}</strong></article>}
function Clients({clients,all,search,setSearch,form,setForm,create,update,message}:any){return <section className="admin-layout mx-client-layout"><form className="mx-box create-form" onSubmit={create}><h2><Plus/> Novo cliente</h2><label>Nome</label><Input value={form.name} onChange={(e:any)=>setForm({...form,name:e.target.value})} required/><label>Usuário</label><Input value={form.username} onChange={(e:any)=>setForm({...form,username:e.target.value})} required/><label>Senha</label><Input type="password" value={form.password} onChange={(e:any)=>setForm({...form,password:e.target.value})} required/><label>MAC (opcional)</label><Input placeholder="00:00:00:00:00:00" value={form.mac} onChange={(e:any)=>setForm({...form,mac:e.target.value})}/><label>Vencimento</label><Input type="date" value={form.expiresAt} onChange={(e:any)=>setForm({...form,expiresAt:e.target.value})} required/><label>Telas simultâneas</label><Input type="number" min="1" max="10" value={form.maxDevices} onChange={(e:any)=>setForm({...form,maxDevices:e.target.value})}/><label>URL da fonte autorizada</label><Input type="url" value={form.sourceUrl} onChange={(e:any)=>setForm({...form,sourceUrl:e.target.value})}/><Button><Plus/> Cadastrar cliente</Button>{message&&<p className="form-message">{message}</p>}</form><section><div className="mx-search"><Search/><Input placeholder={`Buscar entre ${all.length} clientes`} value={search} onChange={(e:any)=>setSearch(e.target.value)}/></div><div className="client-list">{clients.map((c:Client)=><article className="mx-box client-row" key={c.id}><div><h3>{c.name}</h3><p>@{c.username} · vence {new Date(c.expiresAt).toLocaleDateString("pt-BR")}</p><small>MAC: {c.mac||"não vinculado"} · Key: <b>{c.key}</b></small></div><span className={c.status==="active"?"pill active":"pill blocked"}>{c.status==="active"?"Ativo":"Bloqueado"}</span><div className="row-actions"><Button size="sm" variant="outline" onClick={()=>{const d=new Date(c.expiresAt);d.setDate(d.getDate()+30);update(c.id,{expiresAt:d.toISOString()})}}><RefreshCw/> +30 dias</Button><Button size="sm" variant={c.status==="active"?"destructive":"default"} onClick={()=>update(c.id,{status:c.status==="active"?"blocked":"active"})}>{c.status==="active"?<><Ban/> Bloquear</>:<><CheckCircle2/> Ativar</>}</Button></div></article>)}</div></section></section>}
function Plans(){return <section className="mx-plan-grid">{[['30 dias','R$ 30,00'],['60 dias','R$ 50,00'],['1 ano','R$ 90,00']].map(([n,p])=><article className="mx-box mx-plan" key={n}><Package/><small>PLANO MAXON PLAY</small><h2>{n}</h2><strong>{p}</strong><p>Estrutura preparada para vincular cobrança, vencimento e renovação do cliente.</p><Button>Configurar plano</Button></article>)}</section>}
function Module({title,text,icon,action}:{title:string,text:string,icon:React.ReactNode,action?:React.ReactNode}){return <section className="mx-box mx-module"><div className="mx-module-icon">{icon}</div><small>MÓDULO MAXON PLAY</small><h2>{title}</h2><p>{text}</p>{action||<Button>Configurar módulo</Button>}</section>}
function moduleText(s:string){const m:Record<string,string>={financeiro:'Área preparada para receitas, pagamentos, saldos e histórico financeiro.',pedidos:'Gerencie pedidos da loja e acompanhe o status de cada solicitação.',cupons:'Crie e organize cupons promocionais para seus planos.',avisos:'Publique comunicados para clientes e acompanhe avisos importantes.',suporte:'Centralize atendimentos e informações de suporte ao cliente.',apps:'Organize links e instruções dos aplicativos e players compatíveis.',dominios:'Gerencie configurações de domínio e DNS usadas pelo seu projeto.',importar:'Ferramentas para importar e exportar cadastros e configurações.',analytics:'Área de métricas para conteúdos autorizados e uso do serviço.',perfil:'Dados e preferências do administrador do MAXON PLAY.',config:'Configurações gerais, segurança e preferências do painel.'};return m[s]||'Módulo preparado para expansão do painel.'}
function moduleIcon(s:string){const M:Record<string,React.ReactNode>={financeiro:<CircleDollarSign/>,pedidos:<ShoppingBag/>,cupons:<TicketPercent/>,avisos:<Bell/>,suporte:<Headphones/>,apps:<Smartphone/>,dominios:<Globe2/>,importar:<FileUp/>,analytics:<BarChart3/>,perfil:<UserRound/>,config:<Settings/>};return M[s]||<Settings/>}
