import {FormEvent,useEffect,useMemo,useState} from "react";
import {LayoutDashboard,Users,UserPlus,Wallet,CreditCard,Headphones,Settings,PlaySquare,Globe2,Package,Ticket,FileDown,Search,Plus,RefreshCw,Ban,CheckCircle2,Menu,X} from "lucide-react";
import {Button} from "@/components/ui/button";import{Input}from"@/components/ui/input";
type Client={id:string;name:string;username:string;mac:string;key:string;expiresAt:string;status:string;maxDevices:number;lastAccessAt:string|null;hasSource:boolean};
const initial={name:"",username:"",password:"",mac:"",expiresAt:"",maxDevices:"1",sourceUrl:"",notes:""};
const items=[[LayoutDashboard,"Dashboard"],[Users,"Clientes"],[UserPlus,"Novo Cliente"],[Wallet,"Financeiro"],[CreditCard,"Planos"],[Package,"Pacotes"],[Ticket,"Cupons"],[Headphones,"Suporte"],[PlaySquare,"Web Player"],[Globe2,"DNS & Domínios"],[FileDown,"Importar / Exportar"],[Settings,"Configurações"]] as const;
export default function AdminArea(){const[logged,setLogged]=useState(false),[clients,setClients]=useState<Client[]>([]),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[login,setLogin]=useState({username:"admin",password:""}),[form,setForm]=useState(initial),[view,setView]=useState("Dashboard"),[mobile,setMobile]=useState(false);
async function load(){const r=await fetch("/api/admin/clients");if(r.ok){setLogged(true);setClients((await r.json()).clients)}}useEffect(()=>{load()},[]);
async function signIn(e:FormEvent){e.preventDefault();const r=await fetch("/api/auth/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)}),d=await r.json();if(!r.ok)return setMessage(d.error);setMessage("");load()}
async function create(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setMessage(d.error);setForm(initial);setMessage("Cliente criado com sucesso.");setView("Clientes");load()}
async function update(id:string,changes:Record<string,unknown>){const r=await fetch(`/api/admin/clients/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});if(r.ok)load()}
if(!logged)return <div className="mx-login"><form onSubmit={signIn}><img src="/logo-maxonplay.svg"/><small>PAINEL ADMINISTRATIVO</small><h1>Entrar no MAXON PLAY</h1><label>Usuário</label><Input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><label>Senha</label><Input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><Button>Entrar</Button>{message&&<p>{message}</p>}</form></div>;
const now=Date.now(),active=clients.filter(c=>c.status==="active"&&new Date(c.expiresAt).getTime()>=now).length,expired=clients.length-active,due=clients.filter(c=>{const d=new Date(c.expiresAt).getTime()-now;return d>=0&&d<7*864e5}).length;const visible=clients.filter(c=>`${c.name} ${c.username} ${c.mac}`.toLowerCase().includes(search.toLowerCase()));
const Content=()=>{if(view==="Novo Cliente")return <form className="mx-card mx-form" onSubmit={create}><h2>Novo cliente</h2><div className="mx-formgrid"><label>Nome<Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Usuário<Input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/></label><label>Senha<Input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label>MAC<Input value={form.mac} onChange={e=>setForm({...form,mac:e.target.value})}/></label><label>Vencimento<Input type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})} required/></label><label>Telas<Input type="number" min="1" value={form.maxDevices} onChange={e=>setForm({...form,maxDevices:e.target.value})}/></label></div><Button><Plus/>Cadastrar cliente</Button>{message&&<p>{message}</p>}</form>;
if(view==="Clientes")return <><div className="mx-search"><Search/><Input placeholder="Buscar cliente, usuário ou MAC" value={search} onChange={e=>setSearch(e.target.value)}/><Button onClick={()=>setView("Novo Cliente")}><Plus/>Novo</Button></div><div className="mx-table"><div className="mx-tr mx-th"><b>Cliente</b><b>Vencimento</b><b>Status</b><b>Ações</b></div>{visible.map(c=><div className="mx-tr" key={c.id}><div><b>{c.name}</b><small>@{c.username} · {c.mac||"sem MAC"}</small></div><span>{new Date(c.expiresAt).toLocaleDateString("pt-BR")}</span><span className={c.status==="active"?"mx-ok":"mx-off"}>{c.status==="active"?"Ativo":"Bloqueado"}</span><div className="mx-actions"><button onClick={()=>{const d=new Date(c.expiresAt);d.setDate(d.getDate()+30);update(c.id,{expiresAt:d.toISOString()})}}><RefreshCw/>+30</button><button onClick={()=>update(c.id,{status:c.status==="active"?"blocked":"active"})}>{c.status==="active"?<Ban/>:<CheckCircle2/>}</button></div></div>)}</div>;
if(view!=="Dashboard")return <div className="mx-card mx-empty"><h2>{view}</h2><p>Módulo preparado para integração ao MAXON PLAY.</p></div>;
return <><div className="mx-stats"><div><small>SALDO</small><strong>R$ 0,00</strong><span>Disponível</span></div><div><small>VENDAS HOJE</small><strong>R$ 0,00</strong><span>0 vendas</span></div><div><small>ESTE MÊS</small><strong>R$ 0,00</strong><span>0 vendas</span></div></div><div className="mx-card"><div className="mx-cardtitle"><b>Mais vendidos</b><span>Dia&nbsp;&nbsp; Mês&nbsp;&nbsp; Ano</span></div><div className="mx-chart"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><div className="mx-panels"><section><h3>Clientes - Assinaturas</h3><div><b>{active}</b><small>ATIVOS</small><b>{expired}</b><small>INATIVOS</small><b>{clients.length}</b><small>TOTAL</small><b>{due}</b><small>A VENCER</small></div></section><section><h3>Revendas - Assinaturas</h3><div><b>0</b><small>ATIVOS</small><b>0</b><small>INATIVOS</small><b>0</b><small>TOTAL</small><b>0</b><small>A VENCER</small></div></section></div></>};
return <div className="mx-admin"><aside className={mobile?"open":""}><div className="mx-brand"><img src="/logo-maxonplay.svg"/><button onClick={()=>setMobile(false)}><X/></button></div><div className="mx-user">M<div><b>MAXON PLAY</b><small>Administrador</small></div></div><nav>{items.map(([I,n])=><button className={view===n?"active":""} key={n} onClick={()=>{setView(n);setMobile(false)}}><I/>{n}</button>)}</nav></aside><main><header><button className="mx-menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><small>PAINEL ADMINISTRATIVO</small><h1>{view}</h1></div><span className="mx-online">● Online</span></header><Content/></main></div>}
