import { createFileRoute } from "@tanstack/react-router";
import { FormEvent, useEffect, useState } from "react";
import { KeyRound, LogOut, MonitorSmartphone, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/cliente")({component:ClientArea});
type Client={name:string;username:string;mac:string;key:string;expiresAt:string;status:string;maxDevices:number;hasSource:boolean};
export default function ClientArea(){const[mode,setMode]=useState<"account"|"device">("account"),[form,setForm]=useState({username:"",password:"",mac:"",key:""}),[client,setClient]=useState<Client|null>(null),[message,setMessage]=useState("");useEffect(()=>{fetch("/api/client/me").then(r=>r.ok?r.json():null).then(v=>v&&setClient(v.client))},[]);async function login(e:FormEvent){e.preventDefault();setMessage("Entrando...");const r=await fetch("/api/auth/client",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,mode})}),d=await r.json();if(!r.ok)return setMessage(d.error);setClient(d.client);setMessage("")}async function logout(){await fetch("/api/auth/logout",{method:"POST"});setClient(null)}
if(client)return <div className="panel-page"><header className="panel-header"><a href="/"><img src="/logo-maxonplay.svg"/></a><Button variant="outline" onClick={logout}><LogOut/> Sair</Button></header><main className="panel-shell"><p className="panel-kicker">ÁREA DO CLIENTE</p><h1>Olá, {client.name}</h1><p className="panel-muted">Seu acesso MAXON PLAY em um só lugar.</p><div className="panel-grid"><article className="panel-card"><ShieldCheck/><span>Status</span><strong className="status-active">ATIVO</strong></article><article className="panel-card"><KeyRound/><span>Vencimento</span><strong>{new Date(client.expiresAt).toLocaleDateString("pt-BR")}</strong></article><article className="panel-card"><MonitorSmartphone/><span>Dispositivos</span><strong>Até {client.maxDevices}</strong></article></div><section className="panel-card panel-details"><h2>Dados do aparelho</h2><div><span>MAC cadastrado</span><strong>{client.mac||"Ainda não vinculado"}</strong></div><div><span>Key</span><strong>{client.key}</strong></div><div><span>Fonte autorizada</span><strong>{client.hasSource?"Configurada":"Aguardando configuração"}</strong></div></section><div className="panel-actions"><Button asChild size="lg"><a href="/player">Abrir Web Player</a></Button><Button asChild size="lg" variant="outline"><a href="https://wa.me/553175319525">Falar com suporte</a></Button></div></main></div>;
return <div className="panel-page panel-centered"><main className="login-card"><a href="/"><img className="login-logo" src="/logo-maxonplay.svg"/></a><p className="panel-kicker">ÁREA DO CLIENTE</p><h1>Entre no MAXON PLAY</h1><div className="login-tabs"><button className={mode==="account"?"active":""} onClick={()=>setMode("account")}><UserRound/> Usuário e senha</button><button className={mode==="device"?"active":""} onClick={()=>setMode("device")}><MonitorSmartphone/> MAC e Key</button></div><form onSubmit={login}>{mode==="account"?<><label>Usuário</label><Input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required/><label>Senha</label><Input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></>:<><label>MAC do aparelho</label><Input placeholder="00:00:00:00:00:00" value={form.mac} onChange={e=>setForm({...form,mac:e.target.value})} required/><label>Key de ativação</label><Input value={form.key} onChange={e=>setForm({...form,key:e.target.value.toUpperCase()})} required/></>}<Button className="w-full" size="lg">Entrar</Button>{message&&<p className="form-message">{message}</p>}</form><a className="back-link" href="/">← Voltar para o site</a></main></div>}
