/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtivarRouteImport } from './routes/ativar'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAtivacoesRouteImport } from './routes/admin.ativacoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminDispositivosRouteImport } from './routes/admin.dispositivos'
import { Route as AdminFontesRouteImport } from './routes/admin.fontes'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminVendasRouteImport } from './routes/admin.vendas'
import { Route as ApiV1ActivationActivateRouteImport } from './routes/api/v1/activation/activate'
import { Route as ApiV1ActivationValidateRouteImport } from './routes/api/v1/activation/validate'
import { Route as ApiV1DeviceConfigRouteImport } from './routes/api/v1/device/config'
import { Route as ApiV1DeviceHeartbeatRouteImport } from './routes/api/v1/device/heartbeat'
import { Route as ApiV1DeviceRegisterRouteImport } from './routes/api/v1/device/register'
import { Route as ApiV1DeviceStatusRouteImport } from './routes/api/v1/device/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarRoute = AtivarRouteImport.update({
  id: '/ativar',
  path: '/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtivacoesRoute = AdminAtivacoesRouteImport.update({
  id: '/ativacoes',
  path: '/ativacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispositivosRoute = AdminDispositivosRouteImport.update({
  id: '/dispositivos',
  path: '/dispositivos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFontesRoute = AdminFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1ActivationActivateRoute = ApiV1ActivationActivateRouteImport.update({
  id: '/api/v1/activation/activate',
  path: '/api/v1/activation/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ActivationValidateRoute = ApiV1ActivationValidateRouteImport.update({
  id: '/api/v1/activation/validate',
  path: '/api/v1/activation/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceConfigRoute = ApiV1DeviceConfigRouteImport.update({
  id: '/api/v1/device/config',
  path: '/api/v1/device/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceHeartbeatRoute = ApiV1DeviceHeartbeatRouteImport.update({
  id: '/api/v1/device/heartbeat',
  path: '/api/v1/device/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceRegisterRoute = ApiV1DeviceRegisterRouteImport.update({
  id: '/api/v1/device/register',
  path: '/api/v1/device/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeviceStatusRoute = ApiV1DeviceStatusRouteImport.update({
  id: '/api/v1/device/status',
  path: '/api/v1/device/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/cliente': typeof ClienteRoute
  '/health': typeof HealthRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRoute
  '/admin/ativacoes': typeof AdminAtivacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dispositivos': typeof AdminDispositivosRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/v1/activation/activate': typeof ApiV1ActivationActivateRoute
  '/api/v1/activation/validate': typeof ApiV1ActivationValidateRoute
  '/api/v1/device/config': typeof ApiV1DeviceConfigRoute
  '/api/v1/device/heartbeat': typeof ApiV1DeviceHeartbeatRoute
  '/api/v1/device/register': typeof ApiV1DeviceRegisterRoute
  '/api/v1/device/status': typeof ApiV1DeviceStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/cliente': typeof ClienteRoute
  '/health': typeof HealthRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRoute
  '/admin/ativacoes': typeof AdminAtivacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dispositivos': typeof AdminDispositivosRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin': typeof AdminIndexRoute
  '/api/v1/activation/activate': typeof ApiV1ActivationActivateRoute
  '/api/v1/activation/validate': typeof ApiV1ActivationValidateRoute
  '/api/v1/device/config': typeof ApiV1DeviceConfigRoute
  '/api/v1/device/heartbeat': typeof ApiV1DeviceHeartbeatRoute
  '/api/v1/device/register': typeof ApiV1DeviceRegisterRoute
  '/api/v1/device/status': typeof ApiV1DeviceStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/cliente': typeof ClienteRoute
  '/health': typeof HealthRoute
  '/planos': typeof PlanosRoute
  '/player': typeof PlayerRoute
  '/admin/ativacoes': typeof AdminAtivacoesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dispositivos': typeof AdminDispositivosRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/v1/activation/activate': typeof ApiV1ActivationActivateRoute
  '/api/v1/activation/validate': typeof ApiV1ActivationValidateRoute
  '/api/v1/device/config': typeof ApiV1DeviceConfigRoute
  '/api/v1/device/heartbeat': typeof ApiV1DeviceHeartbeatRoute
  '/api/v1/device/register': typeof ApiV1DeviceRegisterRoute
  '/api/v1/device/status': typeof ApiV1DeviceStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ativar'
    | '/cliente'
    | '/health'
    | '/planos'
    | '/player'
    | '/admin/ativacoes'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dispositivos'
    | '/admin/fontes'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/admin/'
    | '/api/v1/activation/activate'
    | '/api/v1/activation/validate'
    | '/api/v1/device/config'
    | '/api/v1/device/heartbeat'
    | '/api/v1/device/register'
    | '/api/v1/device/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar'
    | '/cliente'
    | '/health'
    | '/planos'
    | '/player'
    | '/admin/ativacoes'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dispositivos'
    | '/admin/fontes'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/admin'
    | '/api/v1/activation/activate'
    | '/api/v1/activation/validate'
    | '/api/v1/device/config'
    | '/api/v1/device/heartbeat'
    | '/api/v1/device/register'
    | '/api/v1/device/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ativar'
    | '/cliente'
    | '/health'
    | '/planos'
    | '/player'
    | '/admin/ativacoes'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dispositivos'
    | '/admin/fontes'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/admin/vendas'
    | '/admin/'
    | '/api/v1/activation/activate'
    | '/api/v1/activation/validate'
    | '/api/v1/device/config'
    | '/api/v1/device/heartbeat'
    | '/api/v1/device/register'
    | '/api/v1/device/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtivarRoute: typeof AtivarRoute
  ClienteRoute: typeof ClienteRoute
  HealthRoute: typeof HealthRoute
  PlanosRoute: typeof PlanosRoute
  PlayerRoute: typeof PlayerRoute
  ApiV1ActivationActivateRoute: typeof ApiV1ActivationActivateRoute
  ApiV1ActivationValidateRoute: typeof ApiV1ActivationValidateRoute
  ApiV1DeviceConfigRoute: typeof ApiV1DeviceConfigRoute
  ApiV1DeviceHeartbeatRoute: typeof ApiV1DeviceHeartbeatRoute
  ApiV1DeviceRegisterRoute: typeof ApiV1DeviceRegisterRoute
  ApiV1DeviceStatusRoute: typeof ApiV1DeviceStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar': {
      id: '/ativar'
      path: '/ativar'
      fullPath: '/ativar'
      preLoaderRoute: typeof AtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ativacoes': {
      id: '/admin/ativacoes'
      path: '/ativacoes'
      fullPath: '/admin/ativacoes'
      preLoaderRoute: typeof AdminAtivacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispositivos': {
      id: '/admin/dispositivos'
      path: '/dispositivos'
      fullPath: '/admin/dispositivos'
      preLoaderRoute: typeof AdminDispositivosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fontes': {
      id: '/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AdminFontesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/activation/activate': {
      id: '/api/v1/activation/activate'
      path: '/api/v1/activation/activate'
      fullPath: '/api/v1/activation/activate'
      preLoaderRoute: typeof ApiV1ActivationActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/activation/validate': {
      id: '/api/v1/activation/validate'
      path: '/api/v1/activation/validate'
      fullPath: '/api/v1/activation/validate'
      preLoaderRoute: typeof ApiV1ActivationValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/config': {
      id: '/api/v1/device/config'
      path: '/api/v1/device/config'
      fullPath: '/api/v1/device/config'
      preLoaderRoute: typeof ApiV1DeviceConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/heartbeat': {
      id: '/api/v1/device/heartbeat'
      path: '/api/v1/device/heartbeat'
      fullPath: '/api/v1/device/heartbeat'
      preLoaderRoute: typeof ApiV1DeviceHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/register': {
      id: '/api/v1/device/register'
      path: '/api/v1/device/register'
      fullPath: '/api/v1/device/register'
      preLoaderRoute: typeof ApiV1DeviceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/device/status': {
      id: '/api/v1/device/status'
      path: '/api/v1/device/status'
      fullPath: '/api/v1/device/status'
      preLoaderRoute: typeof ApiV1DeviceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAtivacoesRoute: typeof AdminAtivacoesRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDispositivosRoute: typeof AdminDispositivosRoute
  AdminFontesRoute: typeof AdminFontesRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAtivacoesRoute: AdminAtivacoesRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDispositivosRoute: AdminDispositivosRoute,
  AdminFontesRoute: AdminFontesRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtivarRoute: AtivarRoute,
  ClienteRoute: ClienteRoute,
  HealthRoute: HealthRoute,
  PlanosRoute: PlanosRoute,
  PlayerRoute: PlayerRoute,
  ApiV1ActivationActivateRoute: ApiV1ActivationActivateRoute,
  ApiV1ActivationValidateRoute: ApiV1ActivationValidateRoute,
  ApiV1DeviceConfigRoute: ApiV1DeviceConfigRoute,
  ApiV1DeviceHeartbeatRoute: ApiV1DeviceHeartbeatRoute,
  ApiV1DeviceRegisterRoute: ApiV1DeviceRegisterRoute,
  ApiV1DeviceStatusRoute: ApiV1DeviceStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}